[package]
name = "example-obstacle-avoiding-robot"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
sensor-types = { workspace = true }
sensor-fusion = { workspace = true }
sim-types = { workspace = true }
sim-core = { workspace = true }
sim-sensor = { workspace = true }
route-types = { workspace = true }
route-pathfind = { workspace = true }
cf-spatial = { workspace = true }
mesh-types = { workspace = true }
mesh-io = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
